/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaencapsulamento;

//Import the other classes in the package "model".
import model.Aluno;
import model.Professor;
import model.Diretor;

public class App {

	//"throws Exception" for the name changing rule.
    public static void main(String[] args) throws Exception {
        //Turns the abstract classes into instance.
    	Aluno a1 = new Aluno ("Elliot", 9, "Nenhum");
    	Aluno a2 = new Aluno ("Samantha", 7, "Nenhum");
    	Professor pr = new Professor("Hugo",25, "Professor(a)");
    	Diretor dir = new Diretor("Luiz",42, "Diretor(a)");
    	
    	
        //Set the name changing rule.
    	pr.setNome("Claudia");
        
    	//Returns output in the Console.
        System.out.println("Nome: "+a1.getNome()+" | Idade: "+a1.getIdade()+" | Cargo: "+a1.getCargo());
        System.out.println("Nome: "+a2.getNome()+" | Idade: "+a2.getIdade()+" | Cargo: "+a2.getCargo());
        System.out.println("Nome: "+pr.getNome()+" | Idade: "+pr.getIdade()+" | Cargo: "+pr.getCargo());
        System.out.println("Nome: "+dir.getNome()+" | Idade: "+dir.getIdade()+" | Cargo: "+dir.getCargo());
    }
}

//Tip: Don't put the Workplace in the same place as the project.
//Tip: Delete src/test/java/project package/AppTest.java to stop the getGreeting() error.
//Tip: Ctrl+1 for quick-fix
